[package]
name = "runtime"
version = "0.1.0"
edition = "2024"

[dependencies]
futures = "0.3.31"
gloo = {version = "0.11.0", features = ["futures"]}
wasm-bindgen-futures = "0.4.50"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = {version = "1.47.1", features = ["full"]}

